evaluate-commands %sh{
  kcr init kakoune
}

evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}

plug "andreyorst/plug.kak" noload
plug "dracula/kakoune" theme config %{
    colorscheme dracula
}

define-command lf -params .. -file-completion -docstring "Open files with lf" %{
    connect terminal lf %arg{@}
}

define-command zk-find -params 0 %{
    connect terminal
}

add-highlighter global/number number-lines -relative -hlcursor
add-highlighter global/matching show-matching
