# kcr
evaluate-commands %sh{
    kcr init kakoune
}

# plugins
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "raiguard/one.kak" theme config %{
    colorscheme one-dark
}

set-option global scrolloff 4,4
set-option global ui_options ncurses_set_title=false

set-option global tabstop 4
set-option global indentwidth 4

hook global WinSetOption filetype=(c|cpp) %{
    set-option buffer formatcmd 'clang-format'
}

hook global WinSetOption filetype=gas %{
    set-option window comment_line '#'
}
