#!/bin/sh

export XDG_SESSION_TYPE="wayland"
export XDG_CURRENT_DESKTOP="river"
export XKB_DEFAULT_LAYOUT="us,se"
export XKB_DEFAULT_OPTIONS="caps:swapescape,grp:alt_space_toggle"

exec dbus-run-session river "$@"
