#!/bin/sh

# Usage:
#
# zettel-backlinks [file] [directory]

if ! [ "$#" -eq 2 ]
then
    echo "usage: zettel-backlinks [file] [directory]"
    exit 1
fi

file=$(echo "$1" | sed "s/.*\///")
directory="$2"

backlink=$(
    rg --files-with-matches "\($(basename $file)\)" "$directory" |
    sed "s/.*\///" |
    fzf --layout=reverse --preview-window=down:50% -i --preview="bat --color=always --style=plain $directory/{}"
)

! [ -z "$backlink" ] && echo "$directory/$backlink"
