#!/bin/sh

# Usage:
#
# zettel-find [directory]

if ! [ "$#" -eq 1 ]
then
    echo "usage: zettel-find [directory]"
    exit 1
fi

directory="$1"

zettel=$(
    ls "$directory" |
    fzf --print-query -i --preview="bat --color=always --style=plain $directory/{}"
)

if [ "$?" -eq 1 ]
then
    zettel_file="$(zettel-generate-id $zettel).md"
    echo "# $zettel" > "$directory/$zettel_file"
    echo "$directory/$zettel_file"
else
    zettel_file=$(echo "$zettel" | tail -n 1)
    ! [ -z "$zettel" ] && echo "$directory/$zettel_file"
fi
